version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server/data:/server/data
    restart: always
    init: true

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:8080
    restart: always
    init: true